export const LOAD_POSTS_START = "LOAD_POSTS_START";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_ERROR= "LOAD_POSTS_ERROR";

export const CREATE_POST_START= "CREATE_POST_START";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
