FROM ubuntu:latest
RUN apt-get update && apt-get install -y openjdk-8-jdk
COPY . .
RUN ./gradlew build
RUN ls build/libs/blog-api-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "build/libs/blog-api-0.0.1-SNAPSHOT.jar"]
